export const FILTER_OPTIONS = {
  elements: ['Physical', 'Fire', 'Ice', 'Lightning', 'Wind', 'Quantum', 'Imaginary'],
  paths: [
    'Destruction',
    'Hunt',
    'Erudition',
    'Harmony',
    'Nihility',
    'Preservation',
    'Abundance',
    'Remembrance',
    'Elation',
  ],
  rarities: [5, 4],
  archetypes: [
    'Break-DPS',
    'Buffer',
    'Counter',
    'Debuff DPS',
    'Debuffer',
    'DoT',
    'Elation',
    'Follow-up',
    'Healer',
    'HP-Scaling',
    'Hypercarry',
    'Shielder',
    'Summon',
    'Ultimate-Based',
  ],
} as const
